### ISSUE TITLE
${GIT_BRANCH#origin} evaluates to an empty string

### ISSUE THREAD

**Issue by bwaldvogel** [jenkinsci/build-name-setter-plugin#22]
With the update to latest jenkins (2.163) and latest build-name-setter plugin (1.7.0), the following build name configuration stopped working:

```
${GIT_BRANCH#origin}
```

As a workaround, I was able to switch to:
```
${ENV#origin/,var="GIT_BRANCH"}
```

**Comment by damianszczepanik** [comment]
I believe that is because of update https://wiki.jenkins.io/display/JENKINS/Token+Macro+Plugin from version 1.5.1 to 2.5

**Comment by mingfang** [comment]
${GIT_REVISION,length=8} is also empty/broken

**Comment by krulls** [comment]
then this ticket should be marked done in some way, right?
