### ISSUE TITLE
BUILD_DISPLAY_NAME env var not set in 2.0.0

### ISSUE THREAD

**Issue by kellycampbell** [jenkinsci/build-name-setter-plugin#38]
v2.0.0 broke some of our builds. It seems to be because `BUILD_DISPLAY_NAME` isn't being set correctly anymore.

Here's output from 2.0.0 along with the Docker error it caused:

```
10:59:20 New run name is 'bc-19.04.05-b20-bcd21be52'
10:59:20 [release-19.04.05] $ /bin/sh -xe /tmp/jenkins4067196924725182327.sh
10:59:20 + echo BUILD_DISPLAY_NAME=#20
10:59:20 [Docker] INFO: Parsing buildArgs: --build-arg BUILD_DISPLAY_NAME=$BUILD_DISPLAY_NAME
10:59:27 [Docker] ERROR: Failed to create docker image: org.apache.http.client.ClientProtocolException
10:59:27 ERROR: Build step failed with exception
10:59:27 org.newsclub.net.unix.AFUNIXSocketException: Connection reset by peer
```

Here's an example from 1.7.1:
```
11:07:16 Set build name.
11:07:16 New build name is 'bc-19.04.05-b21-bcd21be52'
11:07:16 [release-19.04.05] $ /bin/sh -xe /tmp/jenkins295434464048951470.sh
11:07:16 + echo BUILD_DISPLAY_NAME=bc-19.04.05-b21-bcd21be52
```

We use a regular (non-pipeline) jenkins project and our Build Name for this plugin is set to `bc-19.04.05-b${BUILD_NUMBER}-${SHORT_GIT_COMMIT}`

We use a groovy script in the Inject Environment plugin settings to set the `SHORT_GIT_COMMIT`:

```
def env = currentBuild.getEnvironment()
def gitCommit = env['GIT_COMMIT']
def shortGitCommit = gitCommit[0..8]

def result = ['SHORT_GIT_COMMIT': shortGitCommit]
return result
```

**Comment by damianszczepanik** [comment]
Yes this feature was removed with version 2 as it was quite problematic when using pipeline.

**Comment by opello** [comment]
Is there any alternative path for getting the same information from another variable?

**Comment by kellycampbell** [comment]
Just curious, how was this problematic with pipelines?

The README still includes this as a primary feature in the first paragraph:
```
Also this plugin updates environment build variable BUILD_DISPLAY_NAME so it's value can be used in other build steps.
```

I think a workaround is to just set the env var ourselves in an execute shell or something like that, but it reduces the value of this plugin greatly in my opinion.

**Comment by damianszczepanik** [comment]
I can restore variable - just let me understand how this is related to the main functionality of this plugin

**Comment by kellycampbell** [comment]
We use it to set our Docker image tags, and then the build name displayed in the builds list matches the tag used when deploying it, e.g. on kubernetes. The workaround I'm using now is to set the variable in a groovy script with the env inject plugin, so now we have the format of the variable contents twice in our config, and there's a chance they might not exactly match if someone makes a mistake when configuring the build.

**Comment by damianszczepanik** [comment]
That workaround sounds to me like the proper solution.

**Comment by kellycampbell** [comment]
I'll close this issue.

For anyone looking for the full workaround I'm using, we have this in the Groovy Script of Environment Injector plugin:

```
def env = currentBuild.getEnvironment()
def buildNumber = env['BUILD_NUMBER']
def gitCommit = env['GIT_COMMIT']
def shortGitCommit = gitCommit[0..8]

def result = ['BUILD_DISPLAY_NAME': 'prefix-' + buildNumber + '-' + shortGitCommit]
return result
```

And then for the Build Name setting on this plugin, `${BUILD_DISPLAY_NAME}`

**Comment by drujd** [comment]
Let me just say that this change really reduces the usefullness of the plugin. Basically the main reason we used it in out builds was to declare the build name and then use it also in shell scripts, git tagging etc.

Now we have to declare it again and again, making sure it is the same in every place. Also, env. variables in build name setter work differently than in other places, e.g. in shell we have to use
``
${GIT_BRANCH#origin/}-${BUILD_NUMBER}
``

but in build name setter plugin, we have to use
``
${GIT_BRANCH#remotes/origin/}-${BUILD_NUMBER}
``

We have a number of builds utilizing the plugin that way and now we have to rewrite everything, making sure we avoid gotchas such as the one above. :(

**Comment by damianszczepanik** [comment]
Will be restored with next release

**Comment by drujd** [comment]
Great news! Thank you!

**Comment by evansj** [comment]
As of today, the [latest version](https://plugins.jenkins.io/build-name-setter) is still 2.0.1, released on May 21st, but the commit which restores the `BUILD_DISPLAY_NAME` variable was on 28th May. @damianszczepanik please could you do another release? Thank you.

**Comment by damianszczepanik** [comment]
Sorry for that - new version is released now

**Comment by evansj** [comment]
Thanks very much @damianszczepanik. The new version Is working fine. 🎉
