### ISSUE TITLE
Release Notes missing

### ISSUE THREAD

**Issue by Helpstone** [jenkinsci/build-name-setter-plugin#44]
The release notes are missing and should be available via https://plugins.jenkins.io!

The official documentation of the plugin https://plugins.jenkins.io/build-name-setter does refer to https://wiki.jenkins.io/display/JENKINS/Build+Name+Setter+Plugin. That's a bit inconveniant, but ok.
But the referred page is not be updated anymore. The latest documentation was for "Version 1.6.9 (Mar 03, 2018)".

When updating plugins I want to read the release notes, so I do recognize important changes. Therefore release notes should be available or at least linked at https://plugins.jenkins.io.

Thanks!

**Comment by damianszczepanik** [comment]
That is gap
The information which was provided is https://github.com/jenkinsci/build-name-setter-plugin/blob/master/src/main/resources/index.jelly#L5
