### ISSUE TITLE
Update build name build step ignores loaded file

### ISSUE THREAD

**Issue by DaDummy** [jenkinsci/build-name-setter-plugin#49]
Version 2.0.2

After updating the plugin to version 2.0.2 version strings loaded from a file are no longer used for the build name as can be seen in the following log output:

```
Getting version from file: C:\some\path\version.txt
Loaded version is r719.WebGL-Standalone
New run name is '#189'
Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: 'r719.WebGL-Standalone', new value: '#189'
```

Downgrading to 2.0.1 appears to be a viable workaround:

```
Getting version from file: C:\some\path\version.txt
Loaded version is r719.WebGL-Standalone
Setting build name to 'r719.WebGL-Standalone'
```

Also please consider publishing a changelog again, so people can appreciate your work.

Right now the only visible change from the updates since 1.6.9 is slowly degrading functionality (first BUILD_DISPLAY_NAME started getting out of sync with the displayed build name and now this bug.)

**Comment by damianszczepanik** [comment]
Hope is the same as #47 which is now fixed and released
