### ISSUE TITLE
Issues with the latest version.

### ISSUE THREAD

**Issue by aruantec** [jenkinsci/build-name-setter-plugin#54]
The latest version added support for the build description which is a welcome change but very bad for us here. We use the build description to display certain information of what happened during the build and as you can imagine the description can contain quite a lot of text. As a result the build name is now a huge mess containing tons of text we don't want to display on the list.

Any option available to avoid that? workaround? I reinstalled the previous version but my build names are messed up still so I hope all my build names aren't screwed.

**Comment by damianszczepanik** [comment]
Then how about checking if provided description is missing/empty and if so - skip update?

**Comment by aruantec** [comment]
Not quite sure what you mean as I have no real control over what's displayed under the history build page except for what I set with the setter plugin. I checked the build history page and noticed there is a div used there to display the description. As a workaround I just forced that div to be hidden in the style.css under the "#buildHistory -desc" section.

The plugin worked fine with previous versions and never had an issue as the description was never displayed. I obviously updated to the latest version which then caused the issue.

**Comment by damianszczepanik** [comment]
Then the requirements for the change is not completed

**Comment by aruantec** [comment]
What do you mean??? not sure what you mean about the change not being completed.

**Comment by damianszczepanik** [comment]
If you are requesting a change we need to agree about the requirements which are not clear now

**Comment by aruantec** [comment]
All I wish is to have a option to determine whatever the description should be displayed or not as that may affect people like us here. Having a option at least we can decide whatever to use that feature or not.

**Comment by damianszczepanik** [comment]
I would add condition which decide when to set/update description. If you provide empty string for description "" then description will stay unchanged. Does not make sens for you? Would it satisfy your needs?

**Comment by damianszczepanik** [comment]
I was trying to reproduce the problem but looks like it is already supported https://github.com/jenkinsci/build-name-setter-plugin/blob/master/src/main/java/org/jenkinsci/plugins/buildnamesetter/Executor.java#L45 like you wish: for empty description updating is not processed.

Then I need more details to reproduce

**Comment by aruantec** [comment]
Sorry for the late reply and thank you for testing it out. After several tests I think is also related to the changes made to the latest Jenkins version. To reproduce the issue install the altest Jenkins version, create a job and add a very long description and using the plugin.

**Comment by aruantec** [comment]
I have made a test and all I did was add HTML support to the description and added a long HTML for testing porpuses. Am not sure if is a issue with the plugin or just a change in Jenkins but if you look the attachment you can see what's going on. 

Hope it helps and if you know a workaround is going to be appreciated.

![issue](https://user-images.githubusercontent.com/10020141/75241585-a4e78980-57c6-11ea-82e6-ad40f469d391.jpg)

**Comment by damianszczepanik** [comment]
Looks like Jenkins feature
