### ISSUE TITLE
How can i using this build name in execute windows batch command?

### ISSUE THREAD

**Issue by burakkp** [jenkinsci/build-name-setter-plugin#56]
Hi Everybody,

I generated build name from this plugin, How can i using this name into the execute windows batch command?

**Comment by damianszczepanik** [comment]
You should be able to see one of the following messages
https://github.com/jenkinsci/build-name-setter-plugin/blob/master/src/main/java/org/jenkinsci/plugins/EnvironmentVarSetter.java#L54-L58 that gives you information about variable
