### ISSUE TITLE
Won't work after a failed build?

### ISSUE THREAD

**Issue by v522zy** [jenkinsci/build-name-setter-plugin#59]
Here is  my case: 
1. In a build, write a version number into ver.txt 
2. set build name from that txt of upper

if in step 1, the build is failed(already generated a version number to ver.txt), 
then the build-name-setter won't work, and the build name is set to a build number, eg #153

**Comment by damianszczepanik** [comment]
Sounds like an expected result.

**Comment by v522zy** [comment]
why?
Dosen't deserve a name when the build is failed?

**Comment by damianszczepanik** [comment]
When the build fails further steps are not performed. Probably lack of ver.txt file causes such problems

**Comment by v522zy** [comment]
Lack of ver.txt is a probability.

Althrouth, sometimes the ver.txt is already generated

Try like this ?

``try:  file of ver.txt is exist
       set a build name from ver.txt
catch()
       set a build name with the build number
