### ISSUE TITLE
plugin does not work with jenkins 2.277.1

### ISSUE THREAD

**Issue by vincentrussell** [jenkinsci/build-name-setter-plugin#63]
### Version report

Jenkins and plugins versions report: Jenkins 2.277.1

This is the fix:

diff --git a/pom.xml b/pom.xml
index a7f02b0..ee84ee5 100644
--- a/pom.xml
+++ b/pom.xml
@@ -4,7 +4,7 @@
     <parent>
         <groupId>org.jenkins-ci.plugins</groupId>
         <artifactId>plugin</artifactId>
-        <version>3.39</version>
+        <version>4.16</version>
     </parent>
 
     <artifactId>build-name-setter</artifactId>
@@ -15,8 +15,9 @@
     <url>https://github.com/jenkinsci/build-name-setter-plugin</url>
 
     <properties>
-        <jenkins.version>2.121.3</jenkins.version>
+        <jenkins.version>2.277.1</jenkins.version>
         <java.level>8</java.level>
+        <asm.version>9.0</asm.version>
     </properties>
 
     <licenses>
@@ -45,16 +46,41 @@
         </developer>
     </developers>
 
+    <dependencyManagement>
+        <dependencies>
+            <dependency>
+                <groupId>org.ow2.asm</groupId>
+                <artifactId>asm</artifactId>
+                <version>${asm.version}</version>
+            </dependency>
+            <dependency>
+                <groupId>org.ow2.asm</groupId>
+                <artifactId>asm-tree</artifactId>
+                <version>${asm.version}</version>
+            </dependency>
+            <dependency>
+                <groupId>org.ow2.asm</groupId>
+                <artifactId>asm-analysis</artifactId>
+                <version>${asm.version}</version>
+            </dependency>
+            <dependency>
+                <groupId>org.ow2.asm</groupId>
+                <artifactId>asm-util</artifactId>
+                <version>${asm.version}</version>
+            </dependency>
+        </dependencies>
+    </dependencyManagement>
+
     <dependencies>
         <dependency>
             <groupId>org.jenkins-ci.plugins</groupId>
             <artifactId>token-macro</artifactId>
-            <version>2.12</version>
+            <version>2.15</version>
         </dependency>
         <dependency>
             <groupId>org.jenkins-ci.plugins</groupId>
             <artifactId>matrix-project</artifactId>
-            <version>1.14</version>
+            <version>1.18</version>
         </dependency>
     </dependencies>

**Comment by paulvi** [comment]
It is not clear what the change is, please format you code with "```" before and after
or better create Pull Request

**Comment by paulvi** [comment]
@vincentrussell Note that 2.277.2 is already out 
https://www.jenkins.io/changelog-stable/

**Comment by vincentrussell** [comment]
k...sorry about that.  I'll try to create a pull request today. Thank you for looking at this.  And I see the note about 2.277.2

**Comment by vincentrussell** [comment]
just created pull request https://github.com/jenkinsci/build-name-setter-plugin/pull/66

Thanks,
