### ISSUE TITLE
[Question] What version of this plugin should work for sure stable with token-macro plugin v2.13?

### ISSUE THREAD

**Issue by paulvi** [jenkinsci/build-name-setter-plugin#65]
What version of this plugin should work for sure stable with token-macro plugin v2.13?

Because of #62 I may need to downgrade this wonderful plugin.
As I cannot (easily) upgrade whole Jenkins

![image](https://user-images.githubusercontent.com/1614482/115349846-efa43c00-a1e6-11eb-95d4-ba3718b21c1f.png)

**Comment by damianszczepanik** [comment]
https://github.com/jenkinsci/build-name-setter-plugin/commit/e43576a0098162a8a94eeb27c627f7f079090143

**Comment by paulvi** [comment]
This is not an answer, 
and the version using token-macro v2.12 and current master using v2.15 is still 2.1.1

CHANGELOG #67 would help to (self-) answer such questions

**Comment by damianszczepanik** [comment]
Maybe. However I'm not sure if this is the true answer and I don't have idea how to maintain this once token-macro updates (what happens quite frequently)

**Comment by paulvi** [comment]
OK, so it is unknown

Please keep CHANGELOG #67 so such question would be answerable
