### ISSUE TITLE
Programmatic build lookup by buildName

### ISSUE THREAD

**Issue by decoursin** [jenkinsci/build-name-setter-plugin#83]
### What feature do you want to see added?

It would be nice if their was some programmatic link between the build number and the buildName as set by the plugin.

Of course, the buildName is initially set to the build number. But with this plugin, the buildName can be changed during the pipeline script.

I would like to be able to programmatically find the build for use with the Jenkins CLI (or Jenkins HTTP API) by the buildName, not by the build number. If there was some connection or link between the two - for example, if I could look up the build number by the buildName, that would suffice.

Unfortunately, however, that's currently not possible. Do you think it's possible? How much work do you think it would take?

Thank you.

**Comment by damianszczepanik** [comment]
build number is a number which is immutable by design - you can play with the name but not with the number

**Comment by decoursin** [comment]
Ok, but it should still be theoretically possible to somehow look up a build by a modifiable value, in this case the name.
